### ISSUE TITLE
Congratulations and a question

### ISSUE THREAD

**Issue by GuidoDipietro** [rvaccarim/genetic_rubik#1]
First of all, I've read your work and I found it incredibly interesting! Definitely caught my attention to learn more about GA.

Now, onto my question:
Have you tried other ways to model a Cube?
For example, describing each piece type as two arrays: orientations and permutations (except centers, they just need 1).

If you need an example of this you can check my JavaScript implementation of a solution checker which uses such an approach [here.](https://github.com/crisszkutnik/fewestmoves-client/blob/master/src/functions/cubeSolve.js)

I wonder if it is possible to achieve shorter solutions using this model, and changing the calculate fitness function to something that (somehow!) calculates how far away from solved the entire cube is.
Counting stickers doesn't exactly sound like the best approach since ¼ of the times a "good" sticker is actually an unsolved piece.

Or perhaps, what about trying a two-phase solver (like Korf's algorithm) where each phase is dealt with using a GA? By using tables to keep track of close-to-solved positions this could be pretty efficient.

I don't know if you're willing to keep playing with this, but I thought it would be an interesting thought to share.

Again, congrats on the work!

**Comment by rvaccarim** [comment]
Hi!, 

I wasn't aware of your project, but it's very cool too! I've always been more interested in speedcubing, but solving in fewer moves is also awesome. 

As for the model, after testing some alternatives, I finally decided to use a very simple representation. However, I had not thought about modeling the cube the way you are suggesting. I'll try to play with your Cube class in order to understand how it works when I have some free time.

In any case, I think that the fitness function should probably be agnostic of the internal model (maybe just harder to code depending on the data structures). But I agree that the function seems far from optimal. While I was developing the project, I made some experiments assigning edges and corners different weights, and also tried penalizing certain states, but in practice the results were pretty much the same so it wasn't worth it. Maybe I just didn't find the correct "magic numbers".

Your idea regarding Korf is very interesting. Once a cube is in a specific group there is a smaller set of valid movements so solutions could be shorter, but movements such as U and R change the cube's state too much and are not very friendly for an evolutionary approach. Or maybe a totally different and advanced fitness function should be used. In any case, going that road looks quite specialized and maybe just implementing Korf alone could be simpler. 😉 

At this moment I'm involved in a different project, but thanks for the ideas and the feedback!!!
